# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Mastering Reinforcement Learning
author: Tim Miller, The University of Queensland
logo: assets/RL.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
#  execute_notebooks: "cache"
  execute_notebooks: "force"
  timeout: 10000
  exclude_patterns:
    - "intro/*.md"
   # - "multi-agent/*.md"
   # - "appendix/*.md"
   # - "single-agent/[a-dA-Z]*.md"
   # - "single-agent/[f-z]*.md"

exclude_patterns:
- .venv
- "LICENSE*"

# Define the name of the latex output file for PDF builds
latex:
#  use_jupyterbook_latex: false
  latex_engine              : xelatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://gibberblot.github.io/rl-notes/intro.html  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-MJY0T8BLG8

# Enable extended syntax
parse:
  myst_extended_syntax:
    - colon_fence
    - dollarmath
    - amsmath
  myst_enable_extensions:
    - html_image
    - colon_fence
    - dollarmath
    - amsmath

# Specify certain folders to be included in the build
# This ensures that the custom raw html sections can find folders which aren't linked by default during the build
# see https://jupyterbook.org/advanced/html.html#raw-html-in-markdown
sphinx:
  local_extensions:
    # Hide any :dropdown: or {toggle} content for LaTeX
    hide_builder_classes: ./sphinx-ext
  config:
    builder_ignore_classes:
        latex:
            - margin
            - tag_html
        html:
            - tag_latex
    latex_elements:
      preamble:  \newcommand\alginput{\mathbf{Input}}
                 \newcommand\algoutput{\mathbf{Output}}
                 \newcommand\algwhile{\mathbf{while}}
                 \newcommand\algfor{\mathbf{for}}
                 \newcommand\algforeach{\mathbf{for\ each}}
                 \newcommand\algdo{\mathbf{do}}
                 \newcommand\algif{\mathbf{if}}
                 \newcommand\algthen{\mathbf{then}}
                 \newcommand\algelse{\mathbf{else}}
                 \newcommand\algelsif{\mathbf{elsif}}
                 \newcommand\algrepeat{\mathbf{repeat}}
                 \newcommand\alguntil{\mathbf{until}}
                 \newcommand\algreturn{\mathbf{return}}
                 \newcommand\algfunction{\mathbf{function}}
                 \newcommand\algprocedure{\mathbf{procedure}}
                 \newcommand\algand{\mathbf{and}}
                 \newcommand\algor{\mathbf{or}}
                 \newcommand\algnot{\mathbf{not}}
    mathjax3_config:
      SVG: true
      tex:
        macros:
          "alginput": "\\mathbf{Input}"
          "algoutput": "\\mathbf{Output}"
          "algwhile": "\\mathbf{while}"
          "algfor": "\\mathbf{for}"
          "algforeach": "\\mathbf{for~each}"
          "algdo": "\\mathbf{do}"
          "algif": "\\mathbf{if}"
          "algthen": "\\mathbf{then}"
          "algelse": "\\mathbf{else}"
          "algelsif": "\\mathbf{elsif}"
          "algrepeat": "\\mathbf{repeat}"
          "alguntil": "\\mathbf{until}"
          "algreturn": "\\mathbf{return}"
          "algfunction": "\\mathbf{function}"
          "algprocedure": "\\mathbf{procedure}"
          "algand": "\\mathbf{and}"
          "algor": "\\mathbf{or}"
          "algnot": "\\mathbf{not}"
    html_extra_path: ['assets']  # This is required to embed the gifs in the html
    latex_toplevel_sectioning: 'part'
  extra_extensions:
    - sphinx_proof
